sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.83.11
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    #    endpoint: oss-cn-hangzhou.aliyuncs.com
    #    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
    #    access-key-secret: U6k1brOZ8gaOIXv3nXbulGTUzy6Pd7
    #    bucket-name: sky-take-out
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8WND2bniKb6q318pkP
    access-key-secret: WgpkCsBNLqPYVoQkC5BycjsayCMje4
    bucket-name: images-big-event
  redis:
    host: 192.168.83.11
    port: 6379
#    password: 0
    database: 0
  wechat:
    appid: wx67e83cae697bbce3
    secret: 2536585cac64cbe8c5b9e7610770ecf8